media:
  input: public/assets
  output: /
content:
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    view:
      fields: [ title, description, date ]
    fields:
      - { name: cover, label: Cover, type: image }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: pubDate, label: Date, type: date }
      - { name: tags, label: Tags, type: string, list: true }
